#! /bin/sh
### BEGIN INIT INFO
# Provides: {scriptname}
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: S 0 1 6
# Short-Description: initscript for {scriptname}
# Description: initscript for {scriptname}
### END INIT INFO

NAME={scriptname}
USER={username}

export HOME=/home/$NAME
 
set -e
 
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
SCRIPT=/usr/local/$NAME/$NAME.sh

d_start() {
	su $USER -l -c "$SCRIPT start"
}
 
d_stop() {
	su $USER -l -c "$SCRIPT stop"
}
 
case "$1" in
	start)
		echo "Starting $NAME..."
		d_start
		;;
	stop)
		echo "Stopping $NAME..."
		d_stop
		;;
	restart|force-reload)
		echo "Restarting $NAME..."
		d_stop
		d_start
	;;
*)
	echo "Usage: sudo /etc/init.d/$NAME {start|stop|restart}" >&2
	exit 1
	;;
esac
 
exit 0
